### ISSUE TITLE
Improve grammar on Progressive Profiling page

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#100]
In reviewing a PR I noticed that the grammar for the progressive profiling page is pretty poor. It would be a good one to update as this is a tricky area which people can often be confused by.

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic-documentation/blob/master/pages/10.Components/03.Forms/02.Progressive%20Profiling/docs.en.md This is the page to be updated

**Comment by oltmanns-leuchtfeuer** [comment]
Made my changes and proposed a PR! :) #117
