### ISSUE TITLE
Show "added through API" event log to timeline

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic-documentation#107]
Mautic 3.1 adds a new event to the lead timeline: "added through API". This means that when a user was created using Mautic's API, it will be shown in the UI. The PRs that add this functionality are https://github.com/mautic/mautic/pull/7538 and https://github.com/mautic/mautic/pull/9067 

I'm not sure if the docs have something about the lead event log (timeline), but it might be useful to end this to the end user docs.

**Comment by RCheesley** [comment]
I don't think we need to add this anywhere as the part about the contact timeline isn't specific about what is shown.
