### ISSUE TITLE
ContactId customfield {id} is not in docs

### ISSUE THREAD

**Issue by tompon** [mautic/mautic-documentation#111]
There is not any evidence in docs, that custom filed {id}, like {contactfield=id}, can be used as well.

Please add it to all necessary places like https://docs.mautic.org/en/setup/variables and so on..

**Comment by RCheesley** [comment]
Hi @tompon please do hit the edit button at the bottom of the page and submit a pull request (or if you are familiar with Git, pull down the repo and make a PR in the usual way) to add any missing variables.

Let me know if you need any help!

**Comment by tompon** [comment]
Hi Ruth, can you please send me the link where I can find how to do it? This is my first time to do such edit..

**Comment by RCheesley** [comment]
Absolutely!

If you go here: https://docs.mautic.org/en/setup/variables there is a link at the bottom of the page.

Here is a quick video which walks you through it: https://www.youtube.com/watch?v=ZToqANMBXe0

Shout if you need any help!

**Comment by tompon** [comment]
Amazing Ruth, thank you!

Done
