### ISSUE TITLE
The page for Upgrade steps to Mautic 3 has several TODOs in the text

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic-documentation#113]
We need to replace the TODOs on https://docs.mautic.org/en/mautic-3-upgrade/upgrade-steps with some actual documentation :slightly_smiling_face:

**Comment by RCheesley** [comment]
We do .... it was a bit of a rush and the last thing on the list!

Would you be able to look into this?

**Comment by ZachHoffman208** [comment]
If StoppingBuck doesn't want to I can look into it

**Comment by StoppingBuck** [comment]
@ZachHoffman208 You can have it :)

**Comment by ZachHoffman208** [comment]
Is there existing documentation for the "Kill switch", or the "api_rate_limiter_cache"?

**Comment by RCheesley** [comment]
> Is there existing documentation for the "Kill switch", or the "api_rate_limiter_cache"?

The 'kill switch' is not user-facing. It is an option that the Product Team have to disable updates if we noticed a problem, or a large number of failures, warn people and send them to a status thread on the forums.

The code that checks for it being enabled is here: https://github.com/mautic/mautic/blob/2.16/upgrade_v3.php#L306

Here is the documentation about the API Rate Limiter Cache: https://developer.mautic.org/#api-rate-limiter

**Comment by StoppingBuck** [comment]
@ZachHoffman208 Did you get a chance to look at this? :slightly_smiling_face:

**Comment by RCheesley** [comment]
https://docs.mautic.org/en/mautic-3-upgrade/getting-started

https://docs.mautic.org/en/mautic-3-upgrade/upgrade-steps

https://docs.mautic.org/en/mautic-3-upgrade/mautic-3-upgrade-errors

Addressed with my updates to these three pages so closing the issue :)
