### ISSUE TITLE
wrong styling of codeblocks at https://docs.mautic.org/en/home/contributing 

### ISSUE THREAD

**Issue by maikroservice** [mautic/mautic-documentation#119]
BUG

Hello,
something appears to go wrong with the markdown to html conversion of the codeblocks parts of the contributing page. 
When visiting the contributing page the links in the table of contents do not work and upon visiting the sections in firefox 80.0 (Mac OSX 10.14.2) one does not see the arrows indicating that this would be collapsible parts, while chrome (85.0.4183.83) shows them but also is unable to render the markdown as can be seen in the attached screenshot. 

Behavior in firefox:
 ![image](https://user-images.githubusercontent.com/20245897/91708078-17c02b80-eb81-11ea-816d-3b36e0497190.png)

additionally, this is also not working at the very bottom of the page for `markdown syntax`

![image](https://user-images.githubusercontent.com/20245897/91709599-4212e880-eb83-11ea-8be1-61c8a857c033.png)

additionally - it would be great if mautic would have an issue template so that new users know which information to put into a new issue. Is this already planned, can I contribute somewhere to the template?

**Comment by oltmanns-leuchtfeuer** [comment]
Hey @maikroservice :) 

I for myself am using Chrome 84.0.4147.135 and MacOS 10.15.4 and hadn't had any markdown rendering issues yet. I also just tested on Firefox 80.0 and had no problems either. 
Maybe we can get some dev insights on this, thus I labeled the post with "help wanted".

Furthermore, we have a bug-reporting template on the mautic/mautic repository. With some smaller changes I think we could use that one for this repo aswell! Thats a pretty good suggestion! :)

**Comment by oltmanns-leuchtfeuer** [comment]
This is the "bug-reporting" template I mentioned: 

[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors


[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by maikroservice** [comment]
@oltmanns-leuchtfeuer fascinating, I tried it again after rebooting and it still does not work - I also tested Safari 12.0.2 now and it does not render the markdown.

**Comment by oltmanns-leuchtfeuer** [comment]
Will close for now, If more people encounter this error we will open it again.
