### ISSUE TITLE
Update documentation on queues

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#152]
Since 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in the local configuration file - we removed the GUI interface with this [commit](https://github.com/mautic/mautic/commit/74b8c3e942636a953b081a285c5b696563806662#diff-0c8e7cb890a2152fe377180fde4a86b3314a41f4933622578bfd53b599f26f29).

We need to update the docs relating to the queue to reflect this and include the required syntax/configuration as an example.

**Comment by fakela** [comment]
@RCheesley I want to work on this addition

**Comment by RCheesley** [comment]
Awesome! 🎉
