### ISSUE TITLE
Add further documentation on types of data sources available under Reports 

### ISSUE THREAD

**Issue by prasannakulkarni333** [mautic/mautic-documentation#160]
The current documentation does not provide any additional information on types of data sources available in reports. 

It might confusing to see so many report types for new users. 

It might be helpful to understand these to think about possible use cases if there is further information on the types of reports possible.

![emaill](https://user-images.githubusercontent.com/30556897/104393803-2a1c7f80-54fa-11eb-9d62-8840f18290fb.PNG)

I have started work on a [branch](https://github.com/prasannakulkarni333/mautic-documentation). I plan to add report types for as mentioned in the screenshot and a short description.

**Comment by RCheesley** [comment]
Fantastic, thank you for working on this and looking forward to reviewing the PR when it's ready 🎉  🚀

**Comment by prasannakulkarni333** [comment]
This has been addressed in approved PR - https://github.com/mautic/mautic-documentation/pull/175
