### ISSUE TITLE
Broken link on 6. Creating Campaigns

### ISSUE THREAD

**Issue by Khaled4** [mautic/mautic-documentation#186]
@RCheesley 
Team, on the documentation covering campaigns (section 06) src ="https://docs.mautic.org/en/campaigns/creating-campaigns"
the following needs to be fixed:

6. Click Launch Campaign Builder to start building your Campaign, and add at least one event. For information about how to use the Campaign Builder, see **Using the Campaign Builder**. 
"Using the Campaign Builder" current broken link is : 
https://docs.mautic.org/en/using-campaign-builder
Correct link needs to be: 
https://docs.mautic.org/en/campaigns/using-campaign-builder

Regards, Khaled

**Comment by RCheesley** [comment]
Thanks for raising it @Khaled4 - at the bottom of every page there is a link to edit the page - would you mind making the edit and creating a pull request for us to review?

Thanks for helping us make the docs better! 🚀

**Comment by Khaled4** [comment]
@RCheesley pleasure. Would always love to help and contribute. However, I am not well versed with GitHub. Let me try though!

**Comment by RCheesley** [comment]
OK - give me a shout on Slack (https://mautic.org/slack) if you get stuck - happy to walk you through the process as it can be a tiny bit daunting the first few times!

**Comment by Khaled4** [comment]
@RCheesley please review, check and advise.

**Comment by RCheesley** [comment]
Fixed by #187 🚀
