### ISSUE TITLE
Add info about Date Files List filters

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-documentation#19]
Hi,

Would it be possible to add to the page:
Those information:

---
### For the date format fields, it is possible to filter with the following values
- last month
- next month
- this month
- today
- tomorrow
- yesterday
- last week
- next week
- this week
- last year
- next year
- this year

![Image of filter with the value yesterday](https://cloud.githubusercontent.com/assets/1235442/9489559/37581dac-4be2-11e5-8486-1f76dacbb672.png)

**Comment by RCheesley** [comment]
Hi peeps, I'm going to close down this issue as I believe we have all the options mentioned documented in one way or another at https://docs.mautic.org/en/contacts/manage-segments#date-options :)
