### ISSUE TITLE
New Email not working

### ISSUE THREAD

**Issue by abdallahtaleb** [mautic/mautic-documentation#201]
Hello Guys,
I am having an issue in Mautic, whenever I press on create new email it does not redirect me to the builder. Adding the link manually to the browser domain.com/s/emails/new gives below error: 
"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."
There are no logs inside mautic to guide me to this. Any idea what the issue could be please?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
