### ISSUE TITLE
Social login doc is missing

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-documentation#21]
Hello @mqueme, there is no doc about https://github.com/mautic/mautic/pull/1552, could you please help ?
Thanks :)

N.

**Comment by stephenjude** [comment]
Hi, 
I want to take up this issue. Please can you provide testing credentials(CLIENT ID & SECRET) for any of the social plugin (Facebook, Twitter, Instagram e.t.c).

Cc: @RCheesley @npracht

**Comment by RCheesley** [comment]
@stephenjude you would need to set that up as developer apps, I believe.

**Comment by stephenjude** [comment]
I am currently testing on the staging server with [mautibox](https://www.mautibox.com/staging/s/dashboard). Is the server not in sync with the staging branch?

**Comment by stephenjude** [comment]
@RCheesley Do I need to get my own credentials? I was thinking there's something that is used generally for testing on the staging server.

**Comment by RCheesley** [comment]
You need to generate your own - Mautibox does not have integrations set up. The staging branch of Mautic is available through the dropdown. You may prefer to test this locally rather than a multi-user environment - let me know if you need a hand with that.

**Comment by stephenjude** [comment]
Okay thanks

**Comment by stephenjude** [comment]
@RCheesley I have completed Mautic setup locally and I also found out that there is a doc for this issue. Please confirm if this is correct.
Link: [social login docs](https://docs.mautic.org/en/plugins/social-login)

**Comment by RCheesley** [comment]
@stephenjude so there is -  could you review to ensure that it is still correct/working as expected? It might be helpful also to add some screenshots?

**Comment by stephenjude** [comment]
Okay

**Comment by oltmanns-leuchtfeuer** [comment]
Updated the Docs - Also added a Screenshot for more clarity! :) 

https://docs.mautic.org/en/plugins/social-login
