### ISSUE TITLE
complete Text Messages settings

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-documentation#22]
To make it work, it must be:

- `+XXXXXXX` format for the contact phone number including the `+` and no space.
- fulfilled in the `mobile` contact field.
- the configuration tab must contain the phone number with same format: `+XXXXXXX`
- the **SID** must be the one of the account, not the one of the phone number
- STOP, STOPALL, UNSUBSCRIBE, CANCEL, END, and QUIT -  will stop customers from receiving messages from that particular Twilio number.

**Comment by oltmanns-leuchtfeuer** [comment]
Added the important Sidenotes by Norman to the Doc.
