### ISSUE TITLE
Improve documentation about dynamic web content

### ISSUE THREAD

**Issue by victorburgos12** [mautic/mautic-documentation#222]
Document url: https://github.com/mautic/mautic-documentation/blob/1bc962fc1acfbf5dd3dc3b8b0cbc702fcc129bd8/pages/11.Components/02.DWC/docs.en.md

On this document is not clear that in order to add DWC to a third party page, you need to insert another code or plugin in addition to the html code.
I use wordpress and to make the HTML work I had to install WP Mautic plugin.

Thanks.

**Comment by RCheesley** [comment]
@victorburgos12 please would you make a PR to address this change? You can do it on the Github page you mentioned by clicking the edit button.

To use any Mautic features like DWC, you will need to have the Mautic tracking code on the pages - that is standard practice but maybe we could make it clearer that this is required - either by manually adding the code, using a tag manager like Google Tag Manager, or by using one of our CMS plugins.

Thanks!

**Comment by victorburgos12** [comment]
Thanks RCeesley, I tried that but it was complicated to understand. I will spend some time learning the process to contribute.
