### ISSUE TITLE
missing email dynamic content doc

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-documentation#23]
Hi @dongilbert, could you please work on Email dynamic content documentation ? https://github.com/mautic/mautic/pull/2574

Thanks a lot for you help.

N.

**Comment by oltmanns-leuchtfeuer** [comment]
There is a Knowledegbase article explaining Dynamic Content in Emails. 
https://kb.mautic.org/knowledgebase/emails/dynamic-content-in-emails
