### ISSUE TITLE
consider automating contributors/authors

### ISSUE THREAD

**Issue by virgilwashere** [mautic/mautic-documentation#24]
## Automate adding contributors to AUTHORS.md

@allcontributors have a bot to _**Recognize All Contributors**_ - Including those that don't push code

https://allcontributors.org/

### Bot Configuration

```json
{
  "files": ["AUTHORS.md"],
  "imageSize": 100,
  "contributorsPerLine": 7,
  "badgeTemplate": "[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)",
  "contributorTemplate": "<%= avatarBlock %><br /><%= contributions %>",
  "types": {
    "custom": {
      "symbol": "🦄",
      "description": "Forum contributions.",
      "link": "[<%= symbol %>](<%= url %> \"<%= description %>\"),"
    }
  },
  "skipCi": "true",
  "contributors": []
}
```

**Comment by RCheesley** [comment]
All Contributors is now enabled across all GitHub repos so closing this PR (although we do need to look into some more funky automation and rolled up reporting at some time, in case anyone wants to pick that up at a later date!)
