### ISSUE TITLE
missing bi-directional zoho documentation

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-documentation#28]
Hello @virlatinus you have linked the doc in your PR https://github.com/mautic/mautic/pull/4068 but the doc is the old one concerning uni-directionnal sync.
Could you make the doc please ?

Thanks a lot,

N.

**Comment by RCheesley** [comment]
I have updated this documentation, refactored to take into account the fact that you now need to create an API key pair (which was incredibly hard to find how to do, incidentally!!) and generally tweaked for accuracy.

https://docs.mautic.org/en/plugins/zoho-crm
