### ISSUE TITLE
Amazon S3 Plugin poorly documented

### ISSUE THREAD

**Issue by skynet** [mautic/mautic-documentation#30]
There's no documentation on how to set up AWS S3 Plugin, what does it do, and how to test it. I got it to work but there's no way to set the region. It will take US-EAST-1 by default.

**Comment by RCheesley** [comment]
Resolved with [this commit](https://github.com/mautic/mautic-documentation/commit/40801febcd345bff633f7fadf560641f71f6effc#diff-d975e2e87546b8022d4668c1346d100c) so closing this issue.
