### ISSUE TITLE
Is "Queue" document is not compatible with mautic v4

### ISSUE THREAD

**Issue by hkarakose** [mautic/mautic-documentation#360]
I have read the document about queue setup: 
https://docs.mautic.org/en/queue

However, I cannot seem to find "Queue Settings" under "Configuration".

**Comment by RCheesley** [comment]
Hi there,

This is documented in the newly updated and WIP documentation: https://mautic-documentation.readthedocs.io/en/latest/queue/queue.html

We hope to launch it soon, just the last few sections are in review.

**Comment by hkarakose** [comment]
Thanks.

The document mentions "Queue Settings" tab. However it does not exist in Configuration page.


![image](https://github.com/mautic/mautic-documentation/assets/406291/25b709a2-8a9c-445c-af25-d05cfc887ac7)
