### ISSUE TITLE
Missing local.php file in the latest Mautic release version (45_mautic-449)

### ISSUE THREAD

**Issue by DevCEDTeam** [mautic/mautic-documentation#361]
Hi Everyone,

The most recent version of Mautic (i.e., 4.4.9 45_mautic-449.zipapp_config) does not extract local.php, or app/config/local.php. How can we change the database settings in the current version to reflect the host, username, password, and MySQL database name?

The WinRAR extractor version 6.21 is shown in the following screenshot.

![local](https://github.com/mautic/mautic-documentation/assets/124220310/172f0220-e4b7-4f9a-bbb3-ea0622a12c6d)

Regards,
Team

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
