### ISSUE TITLE
First page of the Documentation - Before your begin

### ISSUE THREAD

**Issue by Sarvasri** [mautic/mautic-documentation#366]
On the very first page of the documentation it reads...

Before your begin your journey with Mautic, visit the follow topics:

    [Overview of Mautic](https://docs.mautic.org/en/home/overview-of-mautic)
    [Contributing to Mautic](https://docs.mautic.org/en/home/contributing)
    [License Information](https://docs.mautic.org/en/home/license)

It should read Before YOU begin your journey

**Comment by RCheesley** [comment]
Hi there!

Thanks for this, we're about to deploy our new documentation, please check the repo at [https://github.com/mautic/user-documentation](https://github.com/mautic/user-documentation) for the latest version. If you would like to help us with improving the docs, we'd love to help you get started!
