### ISSUE TITLE
Separate out Twilio docs into plugin config and usage

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#53]
When I was following the documentation for setting up Twilio, I noticed that we have everything under how to [configure text messages](https://docs.mautic.org/en/channels/marketing-messages/sms), and nothing showing under plugins where I would expect to find information about how to configure the plugin itself. 

I feel that we should separate [this page out](https://docs.mautic.org/en/channels/marketing-messages/sms) and include [this part](https://docs.mautic.org/en/channels/marketing-messages/sms#configure-text-messages) as a separate page under Plugins in the menu structure explaining how to configure the plugin, linking to it in the information about sending text messages.

**Comment by fakela** [comment]
@RCheesley I would love to work on this issue

**Comment by RCheesley** [comment]
@fakela super, let me know if you need any guidance on creating a new page etc!

**Comment by fakela** [comment]
> @fakela super, let me know if you need any guidance on creating a new page etc!

Alright, I will work on this later today if I have issues I would reach out to you. Thanks a lot
