### ISSUE TITLE
Cron jobs page is missing commands

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#55]
I noticed when I was referring to the Cron jobs page to find the appropriate command for importing contacts or companies that this was missing from the page. 

It would be a really good idea to compare what we have against the [great forum post here](https://forum.mautic.org/t/cron-jobs-whats-the-difference/11177/3) and add those that are missing.

**Comment by swati-thacker13** [comment]
I find information for importing contacts here - https://mauteam.org/mautic/mautic-admins/mautic-cron-jobs-which-ones-to-use/. Is this info up-to-date? 

I would like to work on this ticket. Please assign it to me.

**Comment by swati-thacker13** [comment]
Since the PR has been merged, can you please close this issue?

**Comment by RCheesley** [comment]
Whoops, yes - looks like we didn't link it to the PR - thanks for noticing!
