### ISSUE TITLE
Improve/tidy images on Maxmind article

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#63]
We pulled this together quickly, I would like it if we could improve the images and agree on a standard way that we highlight images.

https://docs.mautic.org/en/setup/maxmind-license

**Comment by fakela** [comment]
@RCheesley the images to use for the maxmind article has to be the same with what's already there but in a much improved manner right?

I would be willing to work on this🙂

**Comment by RCheesley** [comment]
Yes, I would suggest using a standard box, maybe in red, so that it looks a bit tidier than a hand drawn circle.
