### ISSUE TITLE
Add info about scheduled sending of reports

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#65]
With [this PR](https://github.com/mautic/mautic/pull/5205) we introduced the ability to schedule reports to be sent by email but this is missing in the docs.

- [ ] Add to reports documentation
- [ ] Check the Cron command (mautic:reports:scheduler) is on the crons docs and specifically highlighted on the reports page as being needed for scheduled reports

https://docs.mautic.org/en/reports

**Comment by swati-thacker13** [comment]
We also need to update all the screen captures on the https://docs.mautic.org/en/reports page. 

I am working on a PR for this issue.

**Comment by swati-thacker13** [comment]
As part of the above-mentioned commit, I made the following changes:

- Updated all screen captures on the https://docs.mautic.org/en/reports page.
- Added a new section titled 'Schedule' on the Reports page to describe the scheduling reports ability, and added a screenshot for the same.
- Checked the Crons jobs page https://docs.mautic.org/en/setup/cron-jobs. It has the mautic:reports:scheduler command.
