### ISSUE TITLE
Language in the Absolute links section needs to be changed to english

### ISSUE THREAD

**Issue by swati-thacker13** [mautic/mautic-documentation#66]
On the **Contributing to the Mautic documentation** page, the language in the [Absolute links](https://docs.mautic.org/en/home/contributing#absolute-links) section needs to be changed to English.

**Comment by fakela** [comment]
Well , I feel it's being stated as an example on how to write the links in the markdown

**Comment by swati-thacker13** [comment]
I understand that. But why is the example not provided in the English language? To me, it looks a bit awkward.

**Comment by oltmanns-leuchtfeuer** [comment]
Changed to texts into english, as it was easier to change the text instead of explaining why we use latin in the two examples. :)
