### ISSUE TITLE
documentation wrong for Salesforce

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-documentation#75]
I used docs.mautic.org/en/plugins/salesforce#custom-fields-relationships
but it return error “No such column ‘WhoId__c’ on sobject of type mautic_timeline__c”
Then I found another manual mautic.com/help/salesforce-integration-setup and then I setup field: WhoId : Lookup(Lead)
Then works properly.
Form submit actions save in the right column

Can somebody from education team update the docs?

**Comment by RCheesley** [comment]
Thanks for raising the issue, seems like a good one for beginners to get started with so have labelled it as such!

**Comment by fakela** [comment]
I would work on this, @npracht could you please state the exact section of the saleforce documentation that has wrong information

**Comment by fakela** [comment]
<img width="1036" alt="Screenshot 2020-06-26 at 11 49 58 AM" src="https://user-images.githubusercontent.com/39309699/85849626-32ea7580-b7a3-11ea-9648-26994a3e0589.png">

Hi, @npracht when trying to update the docs I saw that the _field : WhoId: Lookup(Lead)_ being located in the docs. Comparing it with link _mautic.com/help/salesforce-integration-setup_ to make the changes this part is cited as the 7 custom field which is a subheading in the docs.

I would need more clarification on the part to be updated

**Comment by kuzmany** [comment]
It looks properly written in Mautic docs https://docs.mautic.org/en/plugins/salesforce
Then the report is mistake.
Sorry for that. Thank you for your time
