### ISSUE TITLE
Broken link in the Salesforce CRM plugin documentation

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic-documentation#77]
Hey, just a quick note to say that the 'these steps' link [here](https://github.com/mautic/mautic-documentation/blob/master/pages/12.Plugins/14.Salesforce/docs.en.md#test-the-plugin) is currently 404. It should be fairly easy to fix if somebody knows there the steps moved to :)

**Comment by RCheesley** [comment]
Thanks @StoppingBuck for taking the time to report this - would you like to fix it? You can use the edit button at the bottom of the page to edit directly in the Github user interface - let me know if you need any help!

**Comment by RCheesley** [comment]
The correct link is now /plugins/plugin-resources/testing-integrations :)

**Comment by RCheesley** [comment]
@StoppingBuck fixed by PR from @fakela !

**Comment by fakela** [comment]
@RCheesley it works now I will effect the similar change for field-mapping its broken too

**Comment by StoppingBuck** [comment]
@RCheesley Sorry, I didn't notice your comment in time. But great that @fakela was able to help 😃
