### ISSUE TITLE
Add information to Gated Video documentation

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic-documentation#80]
As mentioned in https://github.com/mautic/mautic/pull/7365#issuecomment-650809854, we need to make it clear that folks can use the `<video>` element only with proper `<source>` elements to use the Gated Video feature. Please read the comment for all details.

**Comment by fakela** [comment]
@dennisameling even for tracked videos or that's the only exception

**Comment by oltmanns-leuchtfeuer** [comment]
Was fixed in the PR and can be closed :)
