### ISSUE TITLE
Cache & logs now has a new location in Mautic 3.x 

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#82]
I noticed that we missed updating that the cache. and logs are now in /var/cache and /var/logs respectively from Mautic 3.x onwards.

We should do a search/replace to update, and add the info block at the top of the page where it is used heavily telling folk about the change in Mautic 3.x and what to use in Mautic 2.x (e.g. troubleshooting) using the markdown `>>>`

**Comment by swati-thacker13** [comment]
I'll work on this, @RCheesley. Please assign it to me.

**Comment by RCheesley** [comment]
Yes, it would be good to add the info there I think!

**Comment by RCheesley** [comment]
@swati-thacker13 this issue was assigned to you but I'm not sure if we got around to completing it. I've fixed a few references I've found as I've been going through other docs but would be good to do a general find/replace to catch any we might have missed.

**Comment by RCheesley** [comment]
@swati-thacker13 this would be a fairly simple PR - you should be able to do a find/replace globally for app/console and replace with bin/console and likewise app/logs to replace with var/logs

**Comment by swati-thacker13** [comment]
Opened this PR: https://github.com/mautic/mautic-documentation/pull/179 to address this issue.
