### ISSUE TITLE
Another app/console reference

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#84]
Just came across this - a good one for a newcomer so 🙇‍♀️  please leave if you are already contributing 🙇‍♀️  :) 

https://contribute.mautic.org/contributing-to-mautic/developer/local-environment-setup#development-environment. There is a reference here to app/console that needs changing!

**Comment by Adeola-Adesoba** [comment]
Hello,

I will like to work on this but I am not sure what to look for on the link you provided. Thank you.

**Comment by RCheesley** [comment]
@Adeola-Adesoba that's great! On the page I shared, it makes reference to an outdated command:

`app/console`

Since we released Mautic 3, this should now be:

`bin/console`

So this just needs to be updated to reflect the new path.

Does that make more sense? Happy to talk through further if needed!

**Comment by Adeola-Adesoba** [comment]
Hello,

Thank you, it makes more sense but I cannot locate the file that corresponds to that page in your repository.

**Comment by morrme** [comment]
@Adeola-Adesoba here it is:
 https://github.com/mautic/mautic-community-handbook/blob/master/pages/13.contributing/02.developer/04.Local%20environment%20setup/docs.md

**Comment by RCheesley** [comment]
As above, but you can also find an edit link at the bottom of every page on the documentation. 

This link takes you directly to the file on GitHub, which you can then edit when you're logged in and commit your changes/make a pull request.

**Comment by Adeola-Adesoba** [comment]
Done!

**Comment by RCheesley** [comment]
Thanks, sorry for the confusion with it being in a different repo, entirely my fault!
