### ISSUE TITLE
Create a 'configuration' section

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-documentation#93]
Something I noticed when I was suggesting that a new pull request needed to update the documentation is that we don't actually have a section which explains all the different parts of the configuration. 

I wonder if this might be more helpful for a user than having this information scattered across all the different documentation sections. 

Setting up Mautic, most of the time you will work through the configuration step-by-step, so I feel like it would be more helpful if this information was all in one place and we use deep linking to hook people into the relevant section using the header anchor tags when they are elsewhere in the documentation. 

For example if I'm in the email section and mention about the bounce settings we could just link to the header in the configuration > email settings section.

What do you folk think?

Totally open to discussion!

**Comment by swati-thacker13** [comment]
I totally agree with this suggestion, @RCheesley. In fact, there is quite a bit of information about some of these configuration settings that are currently missing/ not documented at all. I had highlighted this bit about email settings in my proposal.

Having a separate Configuration section with all the information in one place makes more sense than having it scattered the way it is all over the docs currently.

**Comment by fakela** [comment]
An additional idea @RCheesley if we have a configuration section then we have sub sections under that explains step-by-step guide to how to configure Mautic for e.g emails etc. And the rest.

**Comment by fakela** [comment]
I may have a slightly different opinion, Currently, I think the doc is easily accessible and sections grouped accordingly and if we put all the configuration into a single section we would have to remove some part of the docs which only content is the basic configuration *For e.g Field Mapping* as to avoid duplication.

I don’t think the configuration information is being scattered in the docs, I think it addresses what needs to be addressed to the user needs at that time. For e.g If a user wants to set up the plugin *icontact* I would prefer all information on how to do so be present on the page.

Also if we remove the configuration subsections in some of the docs, some part of the docs would be sparse and hold little information 

This is my view, it's totally open to criticism as I am willing to learn other views on this

**Comment by oltmanns-leuchtfeuer** [comment]
We now have a pretty good explanation of the Configuration at https://kb.mautic.org/knowledgebase/installation/configuration.
